name: 'Haskell Package Automation'
description: 'Automation for publishing packages to a custom foliage based hackage'
inputs:
  repos:
    description: 'Repos to watch'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: Writing repos file...
      run: echo "${{ inputs.repos }}" > repos
      shell: bash
    - name: Checking for updates...
      run: bash "${{ github.action_path }}"/go.sh
      shell: bash
